import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
   Container,
   Typography,
   Box,
   Grid 
  } 
  from '@mui/material'
import { createClient } from 'contentful';
import BlogData from '../Component/BlogData';

export const getStaticProps = async () => {
  const client = createClient({
    space : 'tftt1ifofyb9',
    accessToken : 'u9kA0KbIGJWoowqqmRzc9c3gy6jT2hGHh5Yl3JgbtwA'
  })

  const res = await client.getEntries({content_type: 'blog'})

  return {
    props : {
      blog : res.items,
      revalidate : 1
    }
  }
}

export default function Home({blog}) {
  return (
    <>
      <Head>
        <title>Azzy's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="lg">
        <Typography
        variant="h3"
        component="h3"
        fontWeight={400}
        color="primary"
        marginTop={2}
        gutterBottom>
          Azzy's Blog
          </Typography>
            <Grid
            container
            columns={{sm: 4 , md : 12}}
            spacing={{sm: 2, md: 4}}
            >
                {blog.map(item => (
                  <BlogData item={item} key={item.sys.id} />
                ))}
            </Grid>
      </Container>
    </>

  )
}
